### ISSUE TITLE
Getting the board_part defition was not found for xilinx.com:au280:part0:1.0

### ISSUE THREAD

**Issue by jeniay** [Xilinx/XilinxBoardStore#104]
When using the board file for Vivado2019.1 I'm getting this error.

maybe it has something to do with the "es1" part in the name?
./part0_pins.xml:<part_info part_name="xcu280-fsvh2892-2L-e-es1">

**Comment by Premduth** [comment]
If this is still open, please file a SR or use the Xilinx forums for further investigation.
