### ISSUE TITLE
au50 production FPGA component part number is incorrect

### ISSUE THREAD

**Issue by MattFromXilinx** [Xilinx/XilinxBoardStore#150]
LINE 28 OF BOARD.XML xcu50-fsvh2104-2L-e
and line 2 of part0_pins.xml xcu50-fsvh2104-2L-e

Both should be xcu50-fsvh2104-2-e

**Comment by Piedone** [comment]
I think this was fixed in the meantime as the current board.xml shows the part name just once and it's the one you mention: https://github.com/Xilinx/XilinxBoardStore/blob/master/boards/Xilinx/au50/production/1.0/board.xml#L60

**Comment by Premduth** [comment]
Closing issue as per comment earlier
