### ISSUE TITLE
Repository claims to be open source but lacks LICENSE file?

### ISSUE THREAD

**Issue by mithro** [Xilinx/XilinxBoardStore#379]
In your README.md file says;
> The Board Store is an open source repository of Board data files designed primarily for use with the Xilinx Vivado Design Suite.

However, I can't seem to find any information about what license this repo is under?

You can find info about adding a license file at https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository 

See https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository , https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/ and https://opensource.guide/legal/

I would recommend talking to @clavin-xlnx if you need advice.

**Comment by Premduth** [comment]
Good catch. This has been fixed

**Comment by Premduth** [comment]
Closing this issue under impression fix is acceptable
