### ISSUE TITLE
Vivado 2020.2 repo update error

### ISSUE THREAD

**Issue by gogo2** [Xilinx/XilinxBoardStore#388]
I get

`ERROR: [Common 17-1475] Error reading json file 'C:/Users/[.,.]/AppData/Roaming/Xilinx/Vivado/2020.2/xhub/board_store/xilinx_board_store/XilinxBoardStore/Vivado/2020.2/.staging/boards/Trenz_Electronic/TE0725LP/1.0/xitem.json'.`

I think it's the same issue as mentioned here
https://forums.xilinx.com/t5/Design-Entry/Vivado-2019-2-Update-Board-Repositories-failing/td-p/1099617

which was fixed I believe here:
https://github.com/Xilinx/XilinxBoardStore/commit/725ca6e160c252d4af7b323e1638429bc08e9b66#diff-910406bb80736645e65416895549d4828ff0dbe87332b9e105f77aedc2aa674a
and 

vivado_2020.2.json should contain lines 3064-3100 of
https://github.com/Xilinx/XilinxBoardStore/blob/2020.1/catalog/vivado_2020.1.json

**Comment by Premduth** [comment]
This came from a bad fix being checked in that has since been reverted. Please confirm and comment and let us know if we can close this issue

**Comment by gogo2** [comment]
Works now, thanks alot
