### ISSUE TITLE
CMOD-s725

### ISSUE THREAD

**Issue by christine225** [Xilinx/XilinxBoardStore#459]
Hello, on the diligent vivado board master file, cmods7-25 exists, but it is not available on the vivado xhub store or here. Could you create a board file for CMODS7-25?

**Comment by Premduth** [comment]
@artvvb can you look into this?

**Comment by artvvb** [comment]
@Premduth The Cmod S7-25 board files have been added in PR#533, this can be closed.

**Comment by Premduth** [comment]
Closing this as per Arthur comments. See PR#533
