### ISSUE TITLE
Vivado flow for Alveo boards removed

### ISSUE THREAD

**Issue by mclayton1000** [Xilinx/XilinxBoardStore#470]
Hello everyone,

the commits 691ebe72af217ed57519e838c48334a94d7e8b89 and 3ccc05c75d37da56f3af9393cd71de61ea362ee8
removed support for Alveo cards in Vivado flow.

Why? Can you revert them, please?

Thank you, best regards.

**Comment by Dylan-GAO** [comment]
I have the same question. Waiting for an answer.

**Comment by ashishd8** [comment]
The change is in place because it was decided to keep Alveo board files internal and can be made available based on the lounge request. Please check below link for board file access -
https://www.xilinx.com/member/alveo-vivado.html

**Comment by vsrunga** [comment]
Yes, this was a deliberate decision from Alveo team
