### ISSUE TITLE
Please resolve issues with Pull 579 and others from OpalKelly

### ISSUE THREAD

**Issue by Premduth** [Xilinx/XilinxBoardStore#581]
Here is the main one with discussions:
https://github.com/Xilinx/XilinxBoardStore/pull/579

**Comment by KristofMcLovin** [comment]
@Premduth  @sabarinaxil I could break this PR into smaller PRs, which could help to uncover the issue. Alternatively, I could manually update the catalog.

We are trying to get these board files out for customer use, are there any updates on this?

**Comment by Premduth** [comment]
@sabarinaxil  please provide an update

**Comment by KristofMcLovin** [comment]
@Premduth You may close this Issue. @sabarinaxil has resolved.

Thanks!
